// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/theshop/ai/internal/app"
	"github.com/theshop/ai/modules/config"
	"github.com/theshop/ai/modules/integrations/gitlab"
	"github.com/theshop/ai/modules/integrations/jira"
	"github.com/theshop/ai/modules/integrations/llm"
)

// InitializeApp 애플리케이션 초기화 구현
func InitializeApp() (*Application, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	
	workspaceManager := ProvideWorkspaceManager()
	
	jiraClient, err := jira.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	
	gitLabClient, err := ProvideGitLabClient(configConfig)
	if err != nil {
		return nil, err
	}
	
	clientMap, err := ProvideMCPClients(configConfig)
	if err != nil {
		return nil, err
	}
	
	mcpLLMService, err := ProvideLLMService(clientMap, configConfig)
	if err != nil {
		return nil, err
	}
	
	integrationService := app.NewIntegrationService(jiraClient, gitLabClient, workspaceManager)
	
	application := ProvideApplication(configConfig, jiraClient, gitLabClient, mcpLLMService, workspaceManager, integrationService, clientMap)
	
	return application, nil
}
