// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/google/wire"
	"github.com/theshop/ai/internal/app"
	"github.com/theshop/ai/modules/config"
	"github.com/theshop/ai/pkg/mcpclient"
)

// InitializeApp 애플리케이션 초기화 구현
func InitializeApp() (*Application, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	
	workspaceManager := ProvideWorkspaceManager()
	
	jiraClient, err := jira.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	
	gitLabClient, err := ProvideGitLabClient(configConfig)
	if err != nil {
		return nil, err
	}
	
	clientMap, err := ProvideMCPClients(configConfig)
	if err != nil {
		return nil, err
	}
	
	mcpLLMService, err := ProvideLLMService(clientMap, configConfig)
	if err != nil {
		return nil, err
	}
	
	integrationService := app.NewIntegrationService(jiraClient, gitLabClient, workspaceManager)
	
	application := ProvideApplication(configConfig, jiraClient, gitLabClient, mcpLLMService, workspaceManager, integrationService, clientMap)
	
	return application, nil
}

// Injectors from wire.go:

// ... existing generated code ...
// Note: Undeclared name errors (e.g., Application, Provide...)
// need to be fixed in the source 'wire.go' file and/or by ensuring
// the corresponding packages and functions exist and are correctly imported there.
// Re-running 'go generate ./...' after fixing dependencies and wire.go is necessary.
